-- =============================================================
-- v001-gps-tracking.sql: GPS tracking partitioned + API keys
-- =============================================================

-- 1. Drop existing non-partitioned ASOP_GPS_TRACKING (if any)
DROP TABLE IF EXISTS ASOP_GPS_TRACKING CASCADE;

-- 2. Create partitioned ASOP_GPS_TRACKING
CREATE TABLE ASOP_GPS_TRACKING
(
    POSITION_ID UUID      NOT NULL,
    VEHICLE_ID  UUID      NOT NULL,
    PATH_ID     UUID      NOT NULL,
    SESSION_ID  UUID,
    GPS_COORD   GEOGRAPHY(POINT, 4326),
    RECORDED_AT TIMESTAMPTZ NOT NULL,
    SPEED_KMH   NUMERIC(5, 2),
    STATUS      VARCHAR(30) DEFAULT 'MOVING',
    CONSTRAINT pk_gps_tracking PRIMARY KEY (POSITION_ID, RECORDED_AT),
    CONSTRAINT fk_gps_vehicle FOREIGN KEY (VEHICLE_ID) REFERENCES ASOP_VEHICLES (VEHICLE_ID) ON DELETE CASCADE,
    CONSTRAINT fk_gps_path FOREIGN KEY (PATH_ID) REFERENCES ASOP_PATHS (PATH_ID),
    CONSTRAINT fk_gps_session FOREIGN KEY (SESSION_ID) REFERENCES ASOP_SESSIONS (SESSION_ID)
) PARTITION BY RANGE (RECORDED_AT);

CREATE INDEX idx_gps_vehicle_time ON ASOP_GPS_TRACKING (VEHICLE_ID, RECORDED_AT DESC);
CREATE INDEX idx_gps_geo ON ASOP_GPS_TRACKING USING GIST (GPS_COORD);

COMMENT ON TABLE ASOP_GPS_TRACKING IS 'GPS-трекинг транспорта (партиционировано по месяцам)';

-- 3. Monthly partitions: 12 months from 2026-09
CREATE TABLE ASOP_GPS_TRACKING_2026_09 PARTITION OF ASOP_GPS_TRACKING FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE ASOP_GPS_TRACKING_2026_10 PARTITION OF ASOP_GPS_TRACKING FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE ASOP_GPS_TRACKING_2026_11 PARTITION OF ASOP_GPS_TRACKING FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE ASOP_GPS_TRACKING_2026_12 PARTITION OF ASOP_GPS_TRACKING FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');
CREATE TABLE ASOP_GPS_TRACKING_2027_01 PARTITION OF ASOP_GPS_TRACKING FOR VALUES FROM ('2027-01-01') TO ('2027-02-01');
CREATE TABLE ASOP_GPS_TRACKING_2027_02 PARTITION OF ASOP_GPS_TRACKING FOR VALUES FROM ('2027-02-01') TO ('2027-03-01');
CREATE TABLE ASOP_GPS_TRACKING_2027_03 PARTITION OF ASOP_GPS_TRACKING FOR VALUES FROM ('2027-03-01') TO ('2027-04-01');
CREATE TABLE ASOP_GPS_TRACKING_2027_04 PARTITION OF ASOP_GPS_TRACKING FOR VALUES FROM ('2027-04-01') TO ('2027-05-01');
CREATE TABLE ASOP_GPS_TRACKING_2027_05 PARTITION OF ASOP_GPS_TRACKING FOR VALUES FROM ('2027-05-01') TO ('2027-06-01');
CREATE TABLE ASOP_GPS_TRACKING_2027_06 PARTITION OF ASOP_GPS_TRACKING FOR VALUES FROM ('2027-06-01') TO ('2027-07-01');
CREATE TABLE ASOP_GPS_TRACKING_2027_07 PARTITION OF ASOP_GPS_TRACKING FOR VALUES FROM ('2027-07-01') TO ('2027-08-01');
CREATE TABLE ASOP_GPS_TRACKING_2027_08 PARTITION OF ASOP_GPS_TRACKING FOR VALUES FROM ('2027-08-01') TO ('2027-09-01');

-- 4. API keys table
CREATE TABLE ASOP_API_KEYS
(
    KEY_ID      UUID         NOT NULL,
    KEY_VALUE   VARCHAR(128) NOT NULL,
    NAME        VARCHAR(100) NOT NULL,
    HMAC_SECRET VARCHAR(128) NOT NULL,
    IS_ACTIVE   BOOLEAN      DEFAULT true,
    RATE_LIMIT  INT          DEFAULT 60,
    CREATED_AT  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    DELETED_AT  TIMESTAMPTZ,
    CONSTRAINT pk_api_keys PRIMARY KEY (KEY_ID),
    CONSTRAINT uq_api_keys_value UNIQUE (KEY_VALUE)
);

COMMENT ON TABLE ASOP_API_KEYS IS 'API-ключи для публичных клиентов (пассажиры)';

-- 5. Seed: passenger app API key
INSERT INTO ASOP_API_KEYS (KEY_ID, KEY_VALUE, NAME, HMAC_SECRET, IS_ACTIVE, RATE_LIMIT)
VALUES (
    '00000000-0000-0000-0000-000000000001',
    'asop-passenger-prod-key-2026',
    'Пассажирское приложение',
    'a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6a7b8c9d0e1f2a3b4c5d6a7b8c9d0e1f2',
    true,
    60
);
