FROM eclipse-temurin:21-jre
RUN apt-get update && apt-get install -y --no-install-recommends openssl curl && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /certs
COPY certs-init.sh /certs-init.sh
RUN chmod +x /certs-init.sh
ENTRYPOINT ["/certs-init.sh"]
