databaseChangeLog:
  - include:
      file: migrations/v001-init.yaml
      relativeToChangelogFile: true
  - include:
      file: migrations/v002-terminal-certs.yaml
      relativeToChangelogFile: true